language: java
dist: trusty
jdk:
- oraclejdk8
cache:
  directories:
  - ~/.m2/repository
  - ~/.p2
  - ~/.sonar/cache
addons:
  sonarcloud:
    organization: "ascendix-github"
script: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
install:
  -
